language: python
python:
  - "3.9"
install:
  - pip install -r requirements.txt
script:
  - python manage.py test lists accounts
  - pip install selenium fabric3
  - python manage.py test functional_tests